/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118472-ge417f939da-20250216"
#endif /* AVUTIL_FFVERSION_H */
